/**
 * game.js — EEG guessing game logic
 * State machine: IDLE -> PLAYING -> FEEDBACK -> (next round or GAME_OVER)
 */

(() => {
  const TOTAL_ROUNDS = 10;

  const BAND_DESCRIPTIONS = {
    delta: 'Delta waves (0.5–4 Hz) are the slowest and highest-amplitude waves, typically seen during deep sleep (stage 3 NREM).',
    theta: 'Theta waves (4–8 Hz) appear during drowsiness, light sleep, and meditative states. Also prominent in hippocampal recordings during memory encoding.',
    alpha: 'Alpha waves (8–13 Hz) are the classic "relaxed-but-awake" rhythm, most prominent over occipital regions when eyes are closed.',
    beta:  'Beta waves (13–30 Hz) are fast, low-amplitude waves associated with active thinking, alertness, and anxiety.',
    gamma: 'Gamma waves (30+ Hz) are very high-frequency oscillations linked to complex cognitive processing and cross-regional integration.',
  };

  const EVENT_DESCRIPTIONS = {
    absence: {
      title: 'Absence Seizure Pattern',
      eeg: 'The hallmark EEG signature is a regular 3 Hz spike-and-wave discharge that starts and stops abruptly. Each complex consists of a sharp positive spike immediately followed by a rounded negative slow wave.',
      features: [
        'Regular 3 Hz (3 per second) spike-and-wave complexes',
        'Generalized — simultaneous across all electrode channels',
        'Abrupt onset and termination (on-off pattern)',
        'Background activity returns immediately to normal',
        'Duration typically 4–20 seconds',
      ],
    },
    focal: {
      title: 'Focal Seizure Onset Pattern',
      eeg: 'Focal onset is identified by a rhythmic discharge evolving in frequency and amplitude over seconds. Activity typically begins as low-amplitude fast activity or rhythmic theta, then builds progressively.',
      features: [
        'Localised to a subset of electrodes (one hemisphere or lobe)',
        'Rhythmic activity evolving in frequency, amplitude, and morphology',
        'Gradual buildup — distinguishes it from the abrupt 3 Hz pattern of absence',
        'Background outside the focus may remain relatively normal',
        'May secondarily generalize to involve both hemispheres',
      ],
    },
    gtc: {
      title: 'Generalized Tonic-Clonic Seizure Activity',
      eeg: 'Two distinct phases: a tonic phase with high-frequency polyspike bursts (10–25 Hz), followed by a clonic phase of repetitive spike-and-slow-wave complexes at 1–4 Hz that progressively slow and diminish.',
      features: [
        'Tonic phase: generalized high-frequency (10–25 Hz) polyspike bursts',
        'Clonic phase: repetitive spike-slow-wave at 1–4 Hz, slowing over time',
        'Very high amplitude throughout — often saturates amplifiers in real recordings',
        'Generalized across all channels simultaneously',
        'Followed by post-ictal suppression (flat or very low-amplitude background)',
      ],
    },
    spindle: {
      title: 'Sleep Spindle',
      eeg: 'Sleep spindles are brief bursts of 12–14 Hz activity with a characteristic waxing-and-waning (fusiform) amplitude envelope, lasting 0.5–2 seconds. Generated by the thalamo-cortical loop, they are the defining feature of stage 2 NREM sleep.',
      features: [
        '12–14 Hz oscillations (sigma band)',
        'Fusiform (spindle-shaped) amplitude envelope — wax, then wane',
        'Duration 0.5–2 seconds',
        'Maximal amplitude over central (Cz) and frontal electrodes',
        'Occur on a background of mixed-frequency stage 2 NREM activity',
        'Often immediately follow a K-complex',
      ],
    },
    kcomplex: {
      title: 'K-complex',
      eeg: 'A K-complex is a high-amplitude, biphasic EEG waveform appearing as a sharp negative deflection immediately followed by a broad positive slow wave. It is the largest single event routinely seen in a normal EEG and is a hallmark of stage 2 NREM sleep.',
      features: [
        'Biphasic: sharp high-amplitude negative wave + broad positive slow wave',
        'Total duration typically 0.5–1.5 seconds',
        'Maximum amplitude over frontal electrodes (Fz, Cz)',
        'Generalized — visible across most channels',
        'Can be triggered by external stimuli (e.g., a sound) during sleep',
        'Often followed immediately by a sleep spindle',
      ],
    },
    triphasic: {
      title: 'Triphasic Waves',
      eeg: 'Triphasic waves are generalized EEG complexes recurring at 1.5–2.5 Hz with a characteristic three-phase morphology: a small negative, then a large positive, then a negative deflection. They have anterior predominance and an anterior-to-posterior lag. They are a marker of metabolic encephalopathy.',
      features: [
        'Three-phase morphology: negative–positive–negative sequence',
        'Recur at 1.5–2.5 Hz (about 2 per second)',
        'Generalized with anterior (frontal) predominance',
        'Associated with hepatic, uremic, or other metabolic encephalopathy',
        'Differentiated from absence by the triphasic shape and slower frequency',
        'Background is typically slow (delta–theta) between complexes',
      ],
    },
    burst_suppression: {
      title: 'Burst Suppression',
      eeg: 'Burst suppression is characterized by alternating periods of near-isoelectric (flat) EEG suppression and bursts of high-amplitude mixed-frequency activity. It indicates severe global brain dysfunction and is seen with deep anesthesia, severe anoxic encephalopathy, or hypothermia.',
      features: [
        'Alternating suppression (near-flat) and high-amplitude bursts',
        'Suppression periods: voltage < 10 µV, typically 1–10 seconds',
        'Bursts: mixed delta, theta, and faster frequencies, high amplitude',
        'Generalized and bilaterally synchronous',
        'Seen in deep anesthesia, post-cardiac arrest, severe hypothermia',
        'Severity correlates with burst-suppression ratio (% time suppressed)',
      ],
    },
  };

  // ── State ──────────────────────────────────────────────────────────────
  let state = 'IDLE';
  let round = 0;
  let score = 0;
  let currentBand  = null;
  let currentEvent = null;
  let selectedBand  = null;
  let selectedEvent = null;

  // ── DOM refs ───────────────────────────────────────────────────────────
  const canvas         = document.getElementById('eeg-canvas');
  const scoreEl        = document.getElementById('score-val');
  const roundEl        = document.getElementById('round-val');
  const bandBtns       = document.querySelectorAll('.btn-toggle[data-band]');
  const eventBtns      = document.querySelectorAll('.btn-event[data-event]');
  const submitBtn      = document.getElementById('submit-btn');
  const feedbackPanel  = document.getElementById('feedback-panel');
  const gameScreen     = document.getElementById('game-screen');
  const gameOverScreen = document.getElementById('game-over');
  const playAgainBtn   = document.getElementById('play-again-btn');

  function resizeCanvas() {
    canvas.width  = canvas.offsetWidth;
    canvas.height = canvas.offsetHeight;
  }

  function renderCurrentSignal() {
    resizeCanvas();
    if (!currentBand) return;
    const difficulty = Math.min(0.9, (round - 1) / TOTAL_ROUNDS);
    const signal = EEG.generateSignal(currentBand, currentEvent, difficulty);
    EEG.renderToCanvas(canvas, signal);
  }

  function startRound() {
    round++;
    state = 'PLAYING';
    selectedBand  = null;
    selectedEvent = null;

    const picked = EEG.pickRound(0.7);
    currentBand  = picked.bandKey;
    currentEvent = picked.eventKey;

    bandBtns.forEach(b => b.classList.remove('selected'));
    eventBtns.forEach(b => {
      b.classList.remove('selected', 'selected-none');
    });
    submitBtn.disabled = true;
    feedbackPanel.classList.add('hidden');
    feedbackPanel.innerHTML = '';

    roundEl.textContent = `${round} / ${TOTAL_ROUNDS}`;
    renderCurrentSignal();
  }

  function checkSubmitReady() {
    submitBtn.disabled = !(selectedBand && selectedEvent !== null);
  }

  bandBtns.forEach(btn => {
    btn.addEventListener('click', () => {
      if (state !== 'PLAYING') return;
      bandBtns.forEach(b => b.classList.remove('selected'));
      btn.classList.add('selected');
      selectedBand = btn.dataset.band;
      checkSubmitReady();
    });
  });

  eventBtns.forEach(btn => {
    btn.addEventListener('click', () => {
      if (state !== 'PLAYING') return;
      eventBtns.forEach(b => b.classList.remove('selected', 'selected-none'));
      selectedEvent = btn.dataset.event;
      btn.classList.add(selectedEvent === 'none' ? 'selected-none' : 'selected');
      checkSubmitReady();
    });
  });

  submitBtn.addEventListener('click', () => {
    if (state !== 'PLAYING') return;
    state = 'FEEDBACK';
    submitBtn.disabled = true;
    showFeedback();
  });

  playAgainBtn.addEventListener('click', () => {
    round = 0;
    score = 0;
    scoreEl.textContent = score;
    gameOverScreen.classList.add('hidden');
    gameScreen.classList.remove('hidden');
    startRound();
  });

  // ── Feedback ───────────────────────────────────────────────────────────
  function showFeedback() {
    const bandCorrect  = selectedBand  === currentBand;
    const eventCorrect = selectedEvent === currentEvent;

    let pointsEarned = 0;
    if (bandCorrect)  pointsEarned += 10;
    if (eventCorrect) pointsEarned += (currentEvent === 'none') ? 5 : 15;
    score += pointsEarned;
    scoreEl.textContent = score;

    let headline, headlineClass;
    if (bandCorrect && eventCorrect) {
      headline = 'Correct';
      headlineClass = 'correct';
    } else if (bandCorrect || eventCorrect) {
      headline = 'Partially correct';
      headlineClass = 'partial';
    } else {
      headline = 'Incorrect';
      headlineClass = 'wrong';
    }

    let detailHTML = '';

    // Band result
    if (!bandCorrect) {
      const correct = EEG.BANDS[currentBand].label;
      const guess   = EEG.BANDS[selectedBand].label;
      detailHTML += `<p class="feedback-detail">
        You selected <strong>${guess}</strong> — this was a <strong>${correct}</strong> signal.<br>
        ${BAND_DESCRIPTIONS[currentBand]}
      </p>`;
    } else {
      detailHTML += `<p class="feedback-detail">
        Correct band: <strong style="color:var(--green)">${EEG.BANDS[currentBand].label}</strong>. ${BAND_DESCRIPTIONS[currentBand]}
      </p>`;
    }

    // Event result
    if (!eventCorrect) {
      if (currentEvent === 'none') {
        detailHTML += `<p class="feedback-detail">
          There was <strong>no special event</strong> in this clip. You selected "${EEG.EVENTS[selectedEvent].label}".
          Review the guide to learn what each event looks like.
        </p>`;
      } else {
        const evInfo = EVENT_DESCRIPTIONS[currentEvent];
        const missed = selectedEvent === 'none';
        detailHTML += `<p class="feedback-detail">
          ${missed
            ? `You selected "None," but this clip contained a <strong style="color:var(--yellow)">${evInfo.title}</strong>.`
            : `You selected "${EEG.EVENTS[selectedEvent].label}," but the event was a <strong style="color:var(--yellow)">${evInfo.title}</strong>.`
          }
        </p>`;
        detailHTML += buildEventGuideHTML(currentEvent, evInfo);
      }
    } else if (currentEvent !== 'none') {
      detailHTML += `<p class="feedback-detail" style="color:var(--green)">
        Correct — you identified the <strong>${EEG.EVENTS[currentEvent].label}</strong> event.
      </p>`;
    }

    if (pointsEarned > 0) {
      detailHTML += `<p class="feedback-points">+${pointsEarned} points</p>`;
    }

    const isLast = round >= TOTAL_ROUNDS;
    detailHTML += `<button class="btn-next" id="next-btn">${isLast ? 'See Results' : 'Next Round'}</button>`;

    feedbackPanel.innerHTML = `
      <div class="feedback-header">
        <span class="feedback-headline ${headlineClass}">${headline}</span>
      </div>
      ${detailHTML}
    `;
    feedbackPanel.classList.remove('hidden');

    // Render inline example canvas if present
    const exCanvas = feedbackPanel.querySelector('.event-example-canvas');
    if (exCanvas) {
      exCanvas.width  = exCanvas.offsetWidth || 700;
      exCanvas.height = exCanvas.offsetHeight || 150;
      const sig = EEG.generateGuideSignal(currentEvent);
      EEG.renderToCanvas(exCanvas, sig, { lineColor: '#e3b341' });
    }

    document.getElementById('next-btn').addEventListener('click', () => {
      if (round >= TOTAL_ROUNDS) endGame();
      else startRound();
    });
  }

  function buildEventGuideHTML(eventKey, evInfo) {
    return `
      <div class="event-guide-block">
        <h3>What does ${evInfo.title} look like?</h3>
        <canvas class="event-example-canvas" style="height:150px"></canvas>
        <p>${evInfo.eeg}</p>
        <ul>
          ${evInfo.features.map(f => `<li>${f}</li>`).join('')}
        </ul>
      </div>
    `;
  }

  // ── End game ───────────────────────────────────────────────────────────
  function endGame() {
    state = 'GAME_OVER';
    gameScreen.classList.add('hidden');

    const maxScore = TOTAL_ROUNDS * 25;
    const pct = Math.round((score / maxScore) * 100);
    let grade = 'Keep Practicing';
    if (pct >= 90)      grade = 'EEG Expert';
    else if (pct >= 70) grade = 'Great Work';
    else if (pct >= 50) grade = 'Good Effort';

    document.getElementById('final-score').textContent = score;
    document.getElementById('max-score').textContent   = maxScore;
    document.getElementById('grade-label').textContent = grade;
    gameOverScreen.classList.remove('hidden');
  }

  window.addEventListener('resize', () => {
    if (state === 'PLAYING' || state === 'FEEDBACK') renderCurrentSignal();
  });

  startRound();
})();
